import {
  ArrowLeftRight,
  Axe,
  Bird,
  Bomb,
  CloudFog,
  CornerUpRight,
  Cross,
  Dices,
  Flame,
  HandCoins,
  HeartPulse,
  Lock,
  MessageCircle,
  ScanEye,
  ScrollText,
  Search,
  Shield,
  Shuffle,
  Syringe,
  Wine,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { ItemId } from "@/lib/game/types";

export const ITEM_ICONS: Record<ItemId, LucideIcon> = {
  loupe: Search,
  irons: Lock,
  hacksaw: Axe,
  flask: Wine,
  adrenal_shot: Syringe,
  marked_bullet: Shuffle,
  counterfeit_chip: ScanEye,
  smoke_bomb: CloudFog,
  silver_tongue: MessageCircle,
  second_wind: HeartPulse,
  riot_vest: Shield,
  molotov: Flame,
  vultures_due: Bird,
  false_confession: ScrollText,
  loaded_dice: Dices,
  bribe: HandCoins,
  point_blank: Zap,
  sleight_of_hand: ArrowLeftRight,
  last_rites: Cross,
  scapegoat: CornerUpRight,
  magnum_load: Bomb,
};
